### ISSUE TITLE
Нужны абсолютные пути

### ISSUE THREAD

**Issue by anomal3** [Agasper/GamePatcher#1]
Лаунчер оказался просто огненным. Но он не поддерживает относительные пути, а так же не воспринимает кириллицу. Если в пути к лаунчеру будет крилица, будет ошибка.
Если в пути будет пробел, будет так же ошибка.

**Comment by anomal3** [comment]
Ну раз автор не отзывается, напишу за него.
Чтобы исправить ошибку с путями, надо использовать путь до exe.
А именно изменить `targetDirectory = args[0];`
в Program.cs меняем 
```csharp 
//targetDirectory = args[0]; //Строка 56
targetDirectory = Application.StartupPath.ToString();
```

**Comment by Agasper** [comment]
Вы можете сделать pull request и я добавлю ваш код в репозитарий

**Comment by anomal3** [comment]
> Вы можете сделать запрос на получение ответа и я добавлю ваш код в репозитарий

Спасибо, я как закончу, я обязательно сделаю бранч.
У меня к Вам вопрос, как поступать с файлами которые от 800мб и более?
не создаётся файл patch_info.txt

**Comment by anomal3** [comment]
И ещё, почему не доступен `Agasper/AgNet`?

**Comment by Agasper** [comment]
> И ещё, почему не доступен `Agasper/AgNet`?

Честно говоря не знаю, возможно случайно при сортировке стер.
Проект восстановил https://github.com/Agasper/AgNet

P.S. Проект был экспериментальный и не завершен, в продакшене использовать настоятельно не рекомендую

**Comment by Agasper** [comment]
На замену AgNet, вышла новая библиотека
https://github.com/Agasper/Neon.NetRpc

**Comment by anomal3** [comment]
> На замену AgNet, вышла новая библиотека https://github.com/Agasper/Neon.NetRpc

Да я щупал её. Шарики которые появляются. Только я пример поглядел и на этом всё, Exampl'ов бы побольше.
Допустим с Character3D
Я когда искал библиотеки выбрал Mirror.

**Comment by Agasper** [comment]
https://github.com/Agasper/Neon.NetRpc более низкоуровневая штука, там не предусмотрены готовые компоненты под Юнити, т.к. чаще всего их все-равно переписывают под себя или пишут с нуля
